// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDI7K7RZnEexjzxmspcKH4JHBe5mjfrPc',
    appId: '1:823889737434:web:833f4618f9aeb41b73d7e3',
    messagingSenderId: '823889737434',
    projectId: 'xtwitter-4bb42',
    authDomain: 'xtwitter-4bb42.firebaseapp.com',
    storageBucket: 'xtwitter-4bb42.appspot.com',
    measurementId: 'G-EL6Y8Q30JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2hyOSOlwdkAvkquFTMbPo9GZBWGxpXFo',
    appId: '1:823889737434:android:03cd4878cdc2773673d7e3',
    messagingSenderId: '823889737434',
    projectId: 'xtwitter-4bb42',
    storageBucket: 'xtwitter-4bb42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK0xrX0-fsoNp1udDez-2cBZhnBHqUQ84',
    appId: '1:823889737434:ios:98f3414e7457ac9273d7e3',
    messagingSenderId: '823889737434',
    projectId: 'xtwitter-4bb42',
    storageBucket: 'xtwitter-4bb42.appspot.com',
    iosBundleId: 'com.example.x',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK0xrX0-fsoNp1udDez-2cBZhnBHqUQ84',
    appId: '1:823889737434:ios:3010cec828e42eeb73d7e3',
    messagingSenderId: '823889737434',
    projectId: 'xtwitter-4bb42',
    storageBucket: 'xtwitter-4bb42.appspot.com',
    iosBundleId: 'com.example.x.RunnerTests',
  );
}
